version: '3'
services:
  server:
    command: yarn start
    volumes:
      - ./server/src:/var/app/src
    build: ./server
  db:
    build: ./db
  db-test:
    ports:
      - "7688:7688"
    environment:
      - NEO4J_dbms_connector_bolt_listen__address=:7688
      - NEO4J_dbms_connector_bolt_advertised__address=:7688
      - NEO4J_AUTH=neo4j/test
    build:
      context: ./db
      dockerfile: Dockerfile
