version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.16.3
    steps:
      - checkout
      - restore_cache:
          name: Restore Cache
          keys:
            - node-dependency-cache-{{ checksum "yarn.lock" }}
            - node-dependency-cache-
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: |
            yarn install
      - save_cache:
          name: Cache Dependencies
          key: node-dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: "[Server] Run Unit Tests"
          command: |
            yarn test
      - run:
          name: Build Integration Test Docker Containers + Run Integration Tests
          command: |
            docker-compose -f docker-int.yml up --build -d
            sleep 5
            docker-compose -f docker-int.yml run tests yarn jest --forceExit test-int/
      - run:
          name: Chat Notification Fail
          when: on_fail
          command: >
            curl --header "Content-Type: application/json"
            --request POST
            --data "{\"cards\":[{\"header\":{\"title\":\"[${CIRCLE_BUILD_NUM}] Oh no! The build is broken! @Giphy broken build\",\"subtitle\":\"${CIRCLE_PROJECT_REPONAME}\",\"imageUrl\":\"https://png.pngtree.com/svg/20170406/icon_failed__1325447.png\",\"imageStyle\":\"IMAGE\"},\"sections\":[{\"widgets\":[{\"keyValue\":{\"topLabel\":\"${CIRCLE_TAG}\",\"content\":\"${CIRCLE_SHA1}\"}}]},{\"widgets\":[{\"buttons\":[{\"textButton\":{\"text\":\"DETAILS\",\"onClick\":{\"openLink\":{\"url\":\"${CIRCLE_BUILD_URL}\"}}}}]}]}]}]}"
            $CHAT_WEBHOOK_URL
workflows:
  version: 2
  master:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - /wip-.*/
  nightly:
  triggers:
    - schedule:
        cron: "0 0 * * *"
        filters:
          branches:
            only:
              - master
