version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12

    steps:
      - checkout

      - restore_cache:
          name: Restore Cache
          keys: 
            - node-dependency-cache-{{ checksum "yarn.lock" }}-{{ checksum "client/yarn.lock" }}-{{ checksum "server/yarn.lock" }}
            - node-dependency-cache-

      - run:
          name: Install Dependencies
          command: |
            yarn install
            cd client
            yarn install
            cd ../server
            yarn install

      - save_cache:
          name: Cache Dependencies
          key: node-dependency-cache-{{ checksum "yarn.lock" }}-{{ checksum "client/yarn.lock" }}-{{ checksum "server/yarn.lock" }}
          paths:
            - node_modules
            - client/node_modules
            - server/node_modules

      - run:
          name: '[Client] Run Unit Tests'
          command: |
            cd client
            yarn test

      - run:
          name: '[Server] Run Unit Tests'
          command: |
            cd server
            yarn test
      
      - setup_remote_docker

      - run: 
          name: Build Integration Test Docker Containers + Run Integration Tests
          command: |
            docker-compose -f docker-int.yml up --build -d
            sleep 5
            docker-compose -f docker-int.yml run tests yarn jest --forceExit test-int/
    
      - run:
          name: Deploy to AWS
          when: on_success
          command: |
            sudo apt install python3-pip
            sudo pip install awscli --upgrade --user
            scripts/docker-machine-pull
            scripts/deploy

      # - run:
      #     name: Chat Notification Fail
      #     when: on_fail
      #     command: >
      #       curl --header "Content-Type: application/json"
      #       --request POST
      #       --data "{\"cards\":[{\"header\":{\"title\":\"[${CIRCLE_BUILD_NUM}] Oh no! The build is broken! @Giphy broken build\",\"subtitle\":\"${CIRCLE_PROJECT_REPONAME}\",\"imageUrl\":\"https://png.pngtree.com/svg/20170406/icon_failed__1325447.png\",\"imageStyle\":\"IMAGE\"},\"sections\":[{\"widgets\":[{\"keyValue\":{\"topLabel\":\"${CIRCLE_TAG}\",\"content\":\"${CIRCLE_SHA1}\"}}]},{\"widgets\":[{\"buttons\":[{\"textButton\":{\"text\":\"DETAILS\",\"onClick\":{\"openLink\":{\"url\":\"${CIRCLE_BUILD_URL}\"}}}}]}]}]}]}"
      #       $CHAT_WEBHOOK_URL
