# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12

    steps:
      - checkout

      - run: yarn install

      - run:
          name: Install client packages
          command: |
            cd client
            yarn install
      
      - run:
          name: Install server packages
          command: |
            cd server
            yarn install

      - run:
          name: Run Client Unit Tests
          command: |
            cd client
            yarn test

      - run:
          name: Run Server Unit Tests
          command: |
            cd server
            yarn test
      
      - setup_remote_docker

      - run: 
          name: Build and Start Integration Test Docker Containers
          command: |
            docker-compose -f docker-int.yml up --build -d

      - run:
          name: Run Server Integration tests
          command: |
            docker-compose -f docker-int.yml run tests yarn jest --forceExit test-int/
