# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12

    steps:
      - checkout

      - restore_cache:
          key: client-dependency-cache-{{ checksum "client/package.json" }}
      
      - run:
          name: ls client
          command: |
            ls
            echo "___"
            cd client
            ls
            echo "___"
            cd node_modules
            ls
    
      - run:
          name: Install client packages
          command: |
            cd client
            yarn install

      - save_cache:
          key: client-dependency-cache-{{ checksum "client/package.json" }}
          paths:
            - client/node_modules

      - restore_cache:
          key: server-dependency-cache-{{ checksum "server/package.json" }}
      
      - run:
          name: ls server
          command: |
            ls
            cd server
            ls
      - run:
          name: Install server packages
          command: |
            cd server
            yarn install
      
      - save_cache:
          key: server-dependency-cache-{{ checksum "server/package.json" }}
          paths:
            - server/node_modules

      - run:
          name: Run Client Unit Tests
          command: |
            cd client
            yarn test

      - run:
          name: Run Server Unit Tests
          command: |
            cd server
            yarn test
      
      - setup_remote_docker

      - run: 
          name: Build Integration Test Docker Containers + Run Integration Tests
          command: |
            docker-compose -f docker-int.yml up --build -d
            sleep 5
            docker-compose -f docker-int.yml run tests yarn jest --forceExit test-int/
