# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout

      - run: yarn install
      
      - run:
          name: Install server packages
          command: |
            cd server
            yarn install
  test: 
    docker:
      - image: circleci/node:8.12
    steps:
      - run:
          name: Run Unit Tests
          command: |
            cd server
            yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
