#!/bin/sh -e

scripts/docker-machine create \
  --driver amazonec2 \
  --amazonec2-region=ap-southeast-2 \
  --amazonec2-iam-instance-profile="topo-demo-docker-host" \
  --amazonec2-open-port 4000 \
  --amazonec2-open-port 5000 \
  --amazonec2-root-size 128 \
  topo-demo
